version: '2.3'

services:
    sample_server:
        container_name: api-sample-container
        image: api-sample-image
        build:
            context: "."
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        #command: bash -c "python3 app.py --host 0.0.0.0 --port 5000 --debug"
